sudo: required
dist: trusty
language: node_js
node_js:
  - "6.3"
services:
  - mongodb
env:
  - NODE_ENV=TEST
before_script:
  - sleep 15
  - mongo ionic-conference-test --eval 'db.addUser("travis", "test");'
git:
  depth: 3
